import { ApiKeyServiceService } from '../../../generated/yandex/cloud/iam/v1/api_key_service';
import { IamTokenServiceService } from '../../../generated/yandex/cloud/iam/v1/iam_token_service';
import { KeyServiceService } from '../../../generated/yandex/cloud/iam/v1/key_service';
import { RoleServiceService } from '../../../generated/yandex/cloud/iam/v1/role_service';
import { ServiceAccountServiceService } from '../../../generated/yandex/cloud/iam/v1/service_account_service';
import { UserAccountServiceService } from '../../../generated/yandex/cloud/iam/v1/user_account_service';
import { YandexPassportUserAccountServiceService } from '../../../generated/yandex/cloud/iam/v1/yandex_passport_user_account_service';
import { Client } from 'nice-grpc';
import { SdkServiceDefinition, Session } from '../../../src/index';
export declare const ApiKeyServiceDef: SdkServiceDefinition<typeof ApiKeyServiceService>;
export declare function ApiKeyService(session?: Session): Client<typeof ApiKeyServiceService, {}>;
export declare const IamTokenServiceDef: SdkServiceDefinition<typeof IamTokenServiceService>;
export declare function IamTokenService(session?: Session): Client<typeof IamTokenServiceService, {}>;
export declare const KeyServiceDef: SdkServiceDefinition<typeof KeyServiceService>;
export declare function KeyService(session?: Session): Client<typeof KeyServiceService, {}>;
export declare const RoleServiceDef: SdkServiceDefinition<typeof RoleServiceService>;
export declare function RoleService(session?: Session): Client<typeof RoleServiceService, {}>;
export declare const ServiceAccountServiceDef: SdkServiceDefinition<typeof ServiceAccountServiceService>;
export declare function ServiceAccountService(session?: Session): Client<typeof ServiceAccountServiceService, {}>;
export declare const UserAccountServiceDef: SdkServiceDefinition<typeof UserAccountServiceService>;
export declare function UserAccountService(session?: Session): Client<typeof UserAccountServiceService, {}>;
export declare const YandexPassportUserAccountServiceDef: SdkServiceDefinition<typeof YandexPassportUserAccountServiceService>;
export declare function YandexPassportUserAccountService(session?: Session): Client<typeof YandexPassportUserAccountServiceService, {}>;
