import { DiskPlacementGroupServiceService } from '../../../generated/yandex/cloud/compute/v1/disk_placement_group_service';
import { DiskServiceService } from '../../../generated/yandex/cloud/compute/v1/disk_service';
import { DiskTypeServiceService } from '../../../generated/yandex/cloud/compute/v1/disk_type_service';
import { HostGroupServiceService } from '../../../generated/yandex/cloud/compute/v1/host_group_service';
import { HostTypeServiceService } from '../../../generated/yandex/cloud/compute/v1/host_type_service';
import { ImageServiceService } from '../../../generated/yandex/cloud/compute/v1/image_service';
import { InstanceServiceService } from '../../../generated/yandex/cloud/compute/v1/instance_service';
import { PlacementGroupServiceService } from '../../../generated/yandex/cloud/compute/v1/placement_group_service';
import { SnapshotServiceService } from '../../../generated/yandex/cloud/compute/v1/snapshot_service';
import { ZoneServiceService } from '../../../generated/yandex/cloud/compute/v1/zone_service';
import { Client } from 'nice-grpc';
import { SdkServiceDefinition, Session } from '../../../src/index';
export declare const DiskPlacementGroupServiceDef: SdkServiceDefinition<typeof DiskPlacementGroupServiceService>;
export declare function DiskPlacementGroupService(session?: Session): Client<typeof DiskPlacementGroupServiceService, {}>;
export declare const DiskServiceDef: SdkServiceDefinition<typeof DiskServiceService>;
export declare function DiskService(session?: Session): Client<typeof DiskServiceService, {}>;
export declare const DiskTypeServiceDef: SdkServiceDefinition<typeof DiskTypeServiceService>;
export declare function DiskTypeService(session?: Session): Client<typeof DiskTypeServiceService, {}>;
export declare const HostGroupServiceDef: SdkServiceDefinition<typeof HostGroupServiceService>;
export declare function HostGroupService(session?: Session): Client<typeof HostGroupServiceService, {}>;
export declare const HostTypeServiceDef: SdkServiceDefinition<typeof HostTypeServiceService>;
export declare function HostTypeService(session?: Session): Client<typeof HostTypeServiceService, {}>;
export declare const ImageServiceDef: SdkServiceDefinition<typeof ImageServiceService>;
export declare function ImageService(session?: Session): Client<typeof ImageServiceService, {}>;
export declare const InstanceServiceDef: SdkServiceDefinition<typeof InstanceServiceService>;
export declare function InstanceService(session?: Session): Client<typeof InstanceServiceService, {}>;
export declare const PlacementGroupServiceDef: SdkServiceDefinition<typeof PlacementGroupServiceService>;
export declare function PlacementGroupService(session?: Session): Client<typeof PlacementGroupServiceService, {}>;
export declare const SnapshotServiceDef: SdkServiceDefinition<typeof SnapshotServiceService>;
export declare function SnapshotService(session?: Session): Client<typeof SnapshotServiceService, {}>;
export declare const ZoneServiceDef: SdkServiceDefinition<typeof ZoneServiceService>;
export declare function ZoneService(session?: Session): Client<typeof ZoneServiceService, {}>;
