import { AuthServiceService } from '../../../../generated/yandex/cloud/mdb/elasticsearch/v1/auth_service';
import { ClusterServiceService } from '../../../../generated/yandex/cloud/mdb/elasticsearch/v1/cluster_service';
import { ResourcePresetServiceService } from '../../../../generated/yandex/cloud/mdb/elasticsearch/v1/resource_preset_service';
import { UserServiceService } from '../../../../generated/yandex/cloud/mdb/elasticsearch/v1/user_service';
import { Client } from 'nice-grpc';
import { SdkServiceDefinition, Session } from '../../../../src/index';
export declare const AuthServiceDef: SdkServiceDefinition<typeof AuthServiceService>;
export declare function AuthService(session?: Session): Client<typeof AuthServiceService, {}>;
export declare const ClusterServiceDef: SdkServiceDefinition<typeof ClusterServiceService>;
export declare function ClusterService(session?: Session): Client<typeof ClusterServiceService, {}>;
export declare const ResourcePresetServiceDef: SdkServiceDefinition<typeof ResourcePresetServiceService>;
export declare function ResourcePresetService(session?: Session): Client<typeof ResourcePresetServiceService, {}>;
export declare const UserServiceDef: SdkServiceDefinition<typeof UserServiceService>;
export declare function UserService(session?: Session): Client<typeof UserServiceService, {}>;
