import { BackupServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/backup_service';
import { ClusterServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/cluster_service';
import { DatabaseServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/database_service';
import { FormatSchemaServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/format_schema_service';
import { MlModelServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/ml_model_service';
import { ResourcePresetServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/resource_preset_service';
import { UserServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/user_service';
import { VersionsServiceService } from '../../../../generated/yandex/cloud/mdb/clickhouse/v1/versions_service';
import { Client } from 'nice-grpc';
import { SdkServiceDefinition, Session } from '../../../../src/index';
export declare const BackupServiceDef: SdkServiceDefinition<typeof BackupServiceService>;
export declare function BackupService(session?: Session): Client<typeof BackupServiceService, {}>;
export declare const ClusterServiceDef: SdkServiceDefinition<typeof ClusterServiceService>;
export declare function ClusterService(session?: Session): Client<typeof ClusterServiceService, {}>;
export declare const DatabaseServiceDef: SdkServiceDefinition<typeof DatabaseServiceService>;
export declare function DatabaseService(session?: Session): Client<typeof DatabaseServiceService, {}>;
export declare const FormatSchemaServiceDef: SdkServiceDefinition<typeof FormatSchemaServiceService>;
export declare function FormatSchemaService(session?: Session): Client<typeof FormatSchemaServiceService, {}>;
export declare const MlModelServiceDef: SdkServiceDefinition<typeof MlModelServiceService>;
export declare function MlModelService(session?: Session): Client<typeof MlModelServiceService, {}>;
export declare const ResourcePresetServiceDef: SdkServiceDefinition<typeof ResourcePresetServiceService>;
export declare function ResourcePresetService(session?: Session): Client<typeof ResourcePresetServiceService, {}>;
export declare const UserServiceDef: SdkServiceDefinition<typeof UserServiceService>;
export declare function UserService(session?: Session): Client<typeof UserServiceService, {}>;
export declare const VersionsServiceDef: SdkServiceDefinition<typeof VersionsServiceService>;
export declare function VersionsService(session?: Session): Client<typeof VersionsServiceService, {}>;
